package CSCI485ClassProject;
/**
 * StatusCode defines the status code that may returns by the {TableManager}
 */
public enum StatusCode {

  SUCCESS,
  INTERNAL_STORAGE_FAILURE,

  TABLE_ALREADY_EXISTS,
  TABLE_CREATION_ATTRIBUTE_INVALID,
  TABLE_CREATION_NO_PRIMARY_KEY,
  TABLE_CREATION_PRIMARY_KEY_NOT_FOUND,
  ATTRIBUTE_TYPE_NOT_SUPPORTED,
  TABLE_NOT_FOUND,
  ATTRIBUTE_ALREADY_EXISTS,
  ATTRIBUTE_NOT_FOUND,

  DATA_RECORD_VALUE_TYPE_UNMATCHED,
  DATA_RECORD_PRIMARY_KEYS_UNMATCHED,
  DATA_RECORD_CREATION_ATTRIBUTES_VALUES_INVALID,
  DATA_RECORD_CREATION_ATTRIBUTES_INVALID,
  DATA_RECORD_CREATION_VALUES_INVALID,
  DATA_RECORD_CREATION_PRIMARY_KEYS_NOT_SET,

  DATA_RECORD_UPDATE_PK_ATTRIBUTES_VALUES_INVALID,
  DATA_RECORD_UPDATE_PK_ATTRIBUTES_INVALID,
  DATA_RECORD_UPDATE_PK_VALUES_INVALID,

  DATA_RECORD_UPDATE_ATTRIBUTES_VALUES_INVALID,
  DATA_RECORD_UPDATE_ATTRIBUTES_INVALID,
  DATA_RECORD_UPDATE_VALUES_INVALID,

  DATA_RECORD_DELETION_PK_ATTRIBUTES_VALUES_INVALID,
  DATA_RECORD_DELETION_PK_ATTRIBUTES_INVALID,
  DATA_RECORD_DELETION_PK_VALUES_INVALID
}